Debouncing
sharkio-dev/sharkio pull request #303
Opened 2023-11-30 17:22 UTC by IdoPeled8

add debounce for test suits.
fix test components.
move state to store.
cleaner code & less code

2023-12-02 13:01 UTC, ypotter commented on client/src/pages/test-suites/RequestModal.tsx
> +const RequestModal = ({
This is not a modal

2023-12-02 13:08 UTC, ypotter commented on client/src/pages/test-suites/TestSuiteMainSection.tsx
> +    if (!testSuiteId || !testId || !currentTest) {
duplicated

2023-12-02 13:14 UTC, ypotter commented on client/src/pages/test-suites/TestSuiteMainSection.tsx
> +  const saveTest = (
Couldn't it be in the testStore?

2023-12-02 13:15 UTC, ypotter commented on client/src/pages/test-suites/TestSuiteMainSection.tsx
> +    if (!testSuiteId || !testId || !currentTest) {
This validation could be in saveTest and save a lot of duplicated code

2023-12-02 13:19 UTC, ypotter commented on client/src/pages/test-suites/TestSuiteMainSection.tsx
>  export const TestSuiteMainSection = () => {
The functions here are repetitive with small changes between them. generally it confuses to read this code and understand the flow. I would this of a way to simplify it.

2023-12-05 11:38 UTC, IdoPeled8 commented
![image](https://github.com/sharkio-dev/sharkio/assets/140278507/0dfd7dac-d3ce-460a-a0dd-0f4f5744f3af)

2023-12-06 08:39 UTC, ypotter requested changes

2023-12-08 14:13 UTC, merged